<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<AssemblyName>ShipsHaveInsides</AssemblyName>
		<AssemblyVersion />
		<FileVersion />
		<Version />
		<Company />
		<Authors />
		<Copyright />
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Nullable>disable</Nullable>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\..\1.6\Assemblies\</OutputPath>
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<LangVersion>10</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\..\1.6\Assemblies\</OutputPath>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<LangVersion>10.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="CompProps\CompProperties_ShipCombatShield.cs" />
		<Compile Remove="CompProps\CompProperties_EngineTrailEnergy.cs" />
		<Compile Remove="Comp\CompEngineTrailEnergy.cs" />
		<Compile Remove="Comp\CompGravshipConversion.cs" />
		<Compile Remove="Alert\AlertMovementBlocked.cs" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="SmashTools, Version=1.6.0.0, Culture=neutral, processorArchitecture=MSIL">
			<HintPath>..\..\..\Vehicle-Framework\1.6\Assemblies\SmashTools.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vehicles">
			<HintPath>..\..\..\Vehicle-Framework\1.6\Assemblies\Vehicles.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" Version="2.3.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" GeneratePathProperty="true" />
		<PackageReference Include="Lib.Harmony" Version="2.4.2" ExcludeAssets="runtime" />
	</ItemGroup>
	<ItemGroup>
		<Publicize Include="Assembly-CSharp" IncludeVirtualMembers="false" />
		<Publicize Include="Vehicles" IncludeVirtualMembers="true" />
	</ItemGroup>
</Project>